title: ""
url: ""

template:
  head: "<meta name=\"google-site-verification\" content=\"-PSXlmvod7yFUB9UrT29Nu8NEeOXZ6ndIKjP7tzLrt8\" />"
  body: "<div class=\"mume markdown-preview  \"><h1><a href=\"https://shinganeuler.github.io/pbrt-v3-chinese\">Physically Based Rendering: From Theory To Implementation 3rd / 基于物理的渲染：从理论到实现第三版<a></h1></div>"
  foot: ""
